name: Stephanie Richardson
favicon: null
layout_spectrum: 0.574304532026872
typography_spectrum: 0.178833652054891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9756808697711676
  lightness: 0.604644269682467
  saturation: 0.667204208439216
  rhythmicContrast: 0.7415459952317178
purpose: []
