name: Stephanie Richardson
favicon: null
layout_spectrum: 0.59419
typography_spectrum: 0.28481
title: 'CF Access Consciousness & Aha Catalyst'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003056'
    - '#007384'
    - '#fcfffe'
    - '#90a7f8'
    - '#cadcfc'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
